name: "Update Linear Issue Status"
description: "A GitHub Action to update the status of Linear issues when PRs are merged."
author: "Your Name"
inputs:
  linear_api_token:
    description: "The Linear API Token"
    required: true
  linear_team_key:
    description: "The Linear Team Key"
    required: true
  to_state_id:
    description: "Update Linear issue to status ID"
    required: true
  main_branch:
    description: "Main branch which release branch merge into"
    required: true
  base_branch:
    description: "Base branch for release branch"
    required: true
  fetch_depth:
    description: "Number of commits to fetch. Default to 300"
    default: "300"
    required: false
  pr_limit:
    description: "Number of github PRs to fetch. Default to 40"
    default: "40"
    required: false
  merge_commit_depth:
    description: "Number of github merge commits in main_branch to linear id lookup. Default to 2. Be careful when setting more than 4" 
    default: "2"
    required: false
  dry_run:
    description: "Whether to run in dry-run mode"
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: Run update_linear_issue_status.sh
      run: ${{ github.action_path }}/update_linear_issue_status.sh
      shell: bash
      env:
        LINEAR_API_TOKEN: ${{ inputs.linear_api_token }}
        LINEAR_TEAM_KEY: ${{ inputs.linear_team_key }}
        TO_STATUS_ID: ${{ inputs.to_state_id }}
        MAIN_BRANCH: ${{ inputs.main_branch }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        FETCH_DEPTH: ${{ inputs.fetch_depth }}
        PR_LIMIT: ${{ inputs.pr_limit }}
        MERGE_COMMIT_DEPTH: ${{ inputs.merge_commit_depth }}
        DRY_RUN: ${{ inputs.dry_run }}
